# Generated by Django 3.2.9 on 2022-01-18 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='participant_ind_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='api.student'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='participant_ind_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='api.student'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='participant_team_1',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='api.sportsteam'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='participant_team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='api.sportsteam'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='participants_ind',
            field=models.ManyToManyField(blank=True, related_name='participant', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='participants_team',
            field=models.ManyToManyField(blank=True, related_name='participants', to='api.SportsTeam'),
        ),
    ]
